### ISSUE TITLE
Initializing error

### ISSUE THREAD

**Issue by tifoha** [icytin/openhierarchy#1]
Hi,  I was trying to installed your framework lately and I find some trubles in your code.
Wen the MySQLCoreDAOFactory trying to upgade the database application is throwing out with jdbc exception. Application doesn't want to starts.
I find the issue in this row:

``` java
UpgradeResult upgradeResult = TableVersionHandler.upgradeDBTables(dataSource, this.getClass().getName(), new XMLDBScriptProvider(this.getClass().getResourceAsStream("MySQL DB script.xml")));
```

It's happends in cese when XMLDBScript trying to execute "CREATE TABLE" script and the target table is alredy exist.
I think you shood add check for the table existence, before creating it in you scripts.

**Comment by icytin** [comment]
Hi, thanks for notice!

This is an OH issue and nothing I´ve written, The issue exist in the 'openhierarchy/OpenHierarchy/hierarchy/src/se/unlogic/hierarchy/core/daos/implementations/mysql/MySQL DB script.xml' just as you say.

I´ve added you write access to this repository, feel free to contribute.

# 

However, I got it working without editing this .xml script. If you look inside the example project there is a script to create the openhierarchy db. "/Example/WebContent/WEB-INF/openhierarchy-clean.sql".
Just execute that script and you should be able to start the application without any errors.

Best Regards,
icytin
