### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by tifoha** [icytin/openhierarchy#2]
Hi!
I am trying to figure out with this project, especialy with how to create modules, but I still don't get in how it works :(.
Do you have any technical documentation, manual, guide or something to help me to understand, how to create different types of modules?

**Comment by icytin** [comment]
Hi!

The big drawback of using openhierarchy is that there is no documentation...

I did update the project a couple of hours after your last issue. I updated the web project -> WebContent -> WEB-INF -> openhierarchy-clean.sql with an example module configured.
You will found the example module source here: openhierarchy /Example/src/com/projecttemplate/modules/example.

When you've started the web application go to the admin menu and check inside the modules and section part. You will find a node named Start or example I think. Click in on that modules gear wheel and you can see how it's configured.

Try to create you own module and add it to the application to understand the configurations. 

Some of the OH standard modules are also configured, for example the login module. You may check at those to see how you can add additional ones.

Feel free to ask, good luck!
